In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
df = pd.read_parquet("../data/processed/complaints_cleaned.parquet")
df.head()

,date_received,product,sub_product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state,zip_code,tags,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,complaint_id,response_delay_days,year,month,year_month
0,2024-11-04 18:11:36,Mortgage,FHA mortgage,Closing on a mortgage,Changes in loan terms during or after closing,NaN,NaN,"Better Mortgage, Inc.",MD,21117,NaN,Phone,2024-11-04 19:12:35+00:00,Closed with explanation,No,10684182,0.0,2024.0,11.0,2024-11
1,2025-03-02 12:43:51,Student loan,Federal student loan servicing,Struggling to repay your loan,"Problem with forgiveness, cancellation, or dis...",This school XXXX XXXXXXXX XXXX XXXX XXXX was u...,NaN,MOHELA,FL,33309,NaN,Web,2025-04-07 16:59:46+00:00,Closed with explanation,No,12285693,36.0,2025.0,3.0,2025-03
2,2025-03-23 12:17:45,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Received bad information about your loan,I was placed in processing forbearance by XXXX...,NaN,MOHELA,CT,060XX,NaN,Web,2025-04-07 15:15:04+00:00,Closed with explanation,No,12661903,15.0,2025.0,3.0,2025-03
3,2025-04-07 21:53:35,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Received bad information about your loan,Type of Issue : Loan balance dispute Loan Serv...,NaN,MOHELA,MI,48307,NaN,Web,2025-04-07 22:04:49+00:00,Closed with explanation,No,12868665,0.0,2025.0,4.0,2025-04
4,2025-04-13 22:18:56,Student loan,Federal student loan servicing,Struggling to repay your loan,Problem with your payment plan,NaN,NaN,MOHELA,VA,22030,NaN,Web,2025-04-13 22:31:23+00:00,Closed with explanation,No,12966383,0.0,2025.0,4.0,2025-04

In [3]:
engine = create_engine("postgresql+psycopg2://admin:admin123@localhost:5432/complaints_db")

In [8]:
df.to_sql(
    "consumer_complaints",
    engine,
    if_exists="replace",
    index=False,
    chunksize=50000,
    method="multi"
)

print("Data loaded into PostgreSQL.")

Data loaded into PostgreSQL.

In [9]:
query = """
SELECT product, COUNT(*) AS total_complaints
FROM consumer_complaints
GROUP BY product
ORDER BY total_complaints DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

                                             product  total_complaints
0  Credit reporting or other personal consumer re...          10608798
1  Credit reporting, credit repair services, or o...           2163774
2                                    Debt collection           1124548
3                                           Mortgage            451637
4                        Checking or savings account            373258
5                                        Credit card            320271
6                        Credit card or prepaid card            206356
7  Money transfer, virtual currency, or money ser...            181659
8                                   Credit reporting            140426
9                                       Student loan            128718