In [1]:
from pathlib import Path

sql_dir = Path("../sql")
sql_dir.mkdir(exist_ok=True)

sql_file = sql_dir / "complaint_analysis_queries.sql"

In [2]:
sql_content = """
-- Query 1: Complaints by Product
SELECT product, COUNT(*) AS total_complaints
FROM consumer_complaints
GROUP BY product
ORDER BY total_complaints DESC;


-- Query 2: Top 20 Companies by Complaint Volume
SELECT company, COUNT(*) AS total_complaints
FROM consumer_complaints
GROUP BY company
ORDER BY total_complaints DESC
LIMIT 20;


-- Query 3: Complaints by State
SELECT state, COUNT(*) AS total_complaints
FROM consumer_complaints
WHERE state IS NOT NULL
GROUP BY state
ORDER BY total_complaints DESC;


-- Query 4: Timely vs Delayed Responses
SELECT timely_response, COUNT(*) AS total
FROM consumer_complaints
GROUP BY timely_response;


-- Query 5: Monthly Complaint Trend
SELECT year_month, COUNT(*) AS total_complaints
FROM consumer_complaints
GROUP BY year_month
ORDER BY year_month;


-- Query 6: Average Response Delay by Product
SELECT product,
       AVG(response_delay_days) AS avg_response_delay
FROM consumer_complaints
WHERE response_delay_days IS NOT NULL
GROUP BY product
ORDER BY avg_response_delay DESC;
"""

with open(sql_file, "w") as file:
    file.write(sql_content)

print("SQL file created successfully:", sql_file)

SQL file created successfully: ../sql/complaint_analysis_queries.sql

In [3]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://admin:admin123@localhost:5432/complaints_db")

In [4]:
query = """
SELECT COUNT(*) AS total_rows
FROM consumer_complaints;
"""

pd.read_sql(query, engine)

   total_rows
0    16019922

In [5]:
query = """
SELECT product, COUNT(*) AS total_complaints
FROM consumer_complaints
GROUP BY product
ORDER BY total_complaints DESC;
"""

product_df = pd.read_sql(query, engine)
product_df

                                              product  total_complaints
0   Credit reporting or other personal consumer re...          10608798
1   Credit reporting, credit repair services, or o...           2163774
2                                     Debt collection           1124548
3                                            Mortgage            451637
4                         Checking or savings account            373258
5                                         Credit card            320271
6                         Credit card or prepaid card            206356
7   Money transfer, virtual currency, or money ser...            181659
8                                    Credit reporting            140426
9                                        Student loan            128718
10                              Vehicle loan or lease             96885
11                            Bank account or service             86198
12  Payday loan, title loan, personal loan, or adv...             32521
13                                      Consumer Loan             31559
14          Payday loan, title loan, or personal loan             30623
15                                       Prepaid card             21566
16                          Debt or credit management              9169
17                                        Payday loan              5528
18                                    Money transfers              5354
19                            Other financial service              1056
20                                   Virtual currency                18

In [6]:
query = """
SELECT company, COUNT(*) AS total_complaints
FROM consumer_complaints
GROUP BY company
ORDER BY total_complaints DESC
LIMIT 20;
"""

company_df = pd.read_sql(query, engine)
company_df

                                   company  total_complaints
0   TRANSUNION INTERMEDIATE HOLDINGS, INC.           4334485
1                            EQUIFAX, INC.           4196638
2      Experian Information Solutions Inc.           3801563
3    BANK OF AMERICA, NATIONAL ASSOCIATION            180808
4                    WELLS FARGO & COMPANY            169640
5                     JPMORGAN CHASE & CO.            169358
6        CAPITAL ONE FINANCIAL CORPORATION            162896
7                           CITIBANK, N.A.            135705
8                      SYNCHRONY FINANCIAL             79859
9                              Block, Inc.             66440
10         Resurgent Capital Services L.P.             66230
11               ENCORE CAPITAL GROUP INC.             61905
12      Portfolio Recovery Associates, LLC             60794
13                              LEXISNEXIS             57990
14                AMERICAN EXPRESS COMPANY             57208
15                     CBC Companies, Inc.             55932
16                            U.S. BANCORP             48022
17               NAVY FEDERAL CREDIT UNION             47009
18          Bread Financial Holdings, Inc.             46607
19                         CL Holdings LLC             46305

In [7]:
query = """
SELECT state, COUNT(*) AS total_complaints
FROM consumer_complaints
WHERE state IS NOT NULL
GROUP BY state
ORDER BY total_complaints DESC;
"""

state_df = pd.read_sql(query, engine)
state_df.head(10)

  state  total_complaints
0    FL           2185015
1    TX           2161213
2    CA           1602564
3    GA           1185169
4    NY            941081
5    IL            686907
6    PA            637097
7    NC            547140
8    NJ            515252
9    MD            398341

In [8]:
query = """
SELECT timely_response, COUNT(*) AS total
FROM consumer_complaints
GROUP BY timely_response;
"""

timely_df = pd.read_sql(query, engine)
timely_df

  timely_response     total
0              No    101494
1             Yes  15918428

In [9]:
query = """
SELECT year_month, COUNT(*) AS total_complaints
FROM consumer_complaints
GROUP BY year_month
ORDER BY year_month;
"""

monthly_df = pd.read_sql(query, engine)
monthly_df.head()

  year_month  total_complaints
0    2012-01                 1
1    2012-12                 1
2    2013-02                 1
3    2013-05                 1
4    2013-08                 1

In [10]:
query = """
SELECT product,
       AVG(response_delay_days) AS avg_response_delay
FROM consumer_complaints
WHERE response_delay_days IS NOT NULL
GROUP BY product
ORDER BY avg_response_delay DESC;
"""

delay_df = pd.read_sql(query, engine)
delay_df

                                              product  avg_response_delay
0                                        Prepaid card            7.473684
1   Payday loan, title loan, personal loan, or adv...            4.679231
2                           Debt or credit management            4.328534
3                             Bank account or service            4.000000
4                                            Mortgage            3.475080
5                         Credit card or prepaid card            3.250000
6   Money transfer, virtual currency, or money ser...            2.717936
7                               Vehicle loan or lease            2.704926
8                                        Student loan            2.699733
9                                         Credit card            2.408235
10                                    Debt collection            2.154687
11                        Checking or savings account            1.400454
12  Credit reporting, credit repair services, or o...            0.880952
13  Credit reporting or other personal consumer re...            0.094714
14          Payday loan, title loan, or personal loan            0.000000

In [11]:
output_dir = Path("../reports/sql_outputs")
output_dir.mkdir(parents=True, exist_ok=True)

In [12]:
product_df.to_csv(output_dir / "complaints_by_product.csv", index=False)
company_df.to_csv(output_dir / "top_companies.csv", index=False)
state_df.to_csv(output_dir / "complaints_by_state.csv", index=False)
timely_df.to_csv(output_dir / "timely_response_summary.csv", index=False)
monthly_df.to_csv(output_dir / "monthly_complaint_trend.csv", index=False)
delay_df.to_csv(output_dir / "response_delay_by_product.csv", index=False)

print("SQL output files saved successfully.")

SQL output files saved successfully.